export const clusterIconStylesNight = [
	{
		textSize: 11,
		anchorText: [1, 0],
		textColor: 'black',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/night_1',
		height: 52,
		width: 53,
	},
	{
		textSize: 12,
		anchorText: [1, 0],
		textColor: 'black',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/night_2',
		height: 55,
		width: 56,
	},
	{
		textSize: 13,
		anchorText: [1, 0],
		textColor: 'black',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/night_3',
		height: 65,
		width: 66,
	},
	{
		textSize: 14,
		anchorText: [1, 0],
		textColor: 'black',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/night_4',
		height: 77,
		width: 78,
	},
	{
		textSize: 15,
		anchorText: [1, 0],
		textColor: 'black',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/night_5',
		height: 89,
		width: 90,
	},
];
export const clusterIconStylesDay = [
	{
		textSize: 11,
		anchorText: [1, 0],
		textColor: 'white',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/day_1',
		height: 52,
		width: 53,
	},
	{
		textSize: 12,
		anchorText: [1, 0],
		textColor: 'white',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/day_2',
		height: 55,
		width: 56,
	},
	{
		textSize: 13,
		anchorText: [1, 0],
		textColor: 'white',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/day_3',
		height: 65,
		width: 66,
	},
	{
		textSize: 14,
		anchorText: [1, 0],
		textColor: 'white',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/day_4',
		height: 77,
		width: 78,
	},
	{
		textSize: 15,
		anchorText: [1, 0],
		textColor: 'white',
		url: 'https://entwicklung.estefan.de/neuefische/clusterer/png/day_5',
		height: 89,
		width: 90,
	},
];
